/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2019-03-22 18:31:00 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@isilo.db.elephantsql.com:5432/qwjszpap -C -t users -t employees -t performance_reviews -t feedback -s public
 *
 */

export type Status = 'assigned' | 'done' | 'in-progress';
export type UserRole = 'admin' | 'employee';

export namespace UsersFields {
    export type id = number;
    export type username = string | null;
    export type password = string | null;
    export type role = UserRole | null;

}

export interface Users {
    id: UsersFields.id;
    username: UsersFields.username;
    password: UsersFields.password;
    role: UsersFields.role;

}

export namespace EmployeesFields {
    export type id = number;
    export type name = string;
    export type post = string | null;
    export type department = string | null;
    export type location = string | null;

}

export interface Employees {
    id: EmployeesFields.id;
    name: EmployeesFields.name;
    post: EmployeesFields.post;
    department: EmployeesFields.department;
    location: EmployeesFields.location;

}

export namespace PerformanceReviewsFields {
    export type id = number;
    export type empId = number | null;
    export type dueDate = Date | null;

}

export interface PerformanceReviews {
    id: PerformanceReviewsFields.id;
    empId: PerformanceReviewsFields.empId;
    dueDate: PerformanceReviewsFields.dueDate;

}

export namespace FeedbackFields {
    export type id = number | null;
    export type reviewerId = number | null;
    export type assignedDate = Date | null;
    export type status = Status | null;
    export type response = Object | null;

}

export interface Feedback {
    id: FeedbackFields.id;
    reviewerId: FeedbackFields.reviewerId;
    assignedDate: FeedbackFields.assignedDate;
    status: FeedbackFields.status;
    response: FeedbackFields.response;

}
